import { defineType, defineField } from 'sanity';

export const homepage = defineType({
  name: 'homepage',
  type: 'document',
  title: 'Homepage',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'programs', title: 'Program Categories' },
    { name: 'whyChooseUs', title: 'Why Choose Us' },
    { name: 'cta', title: 'CTA Banner' },
  ],
  fields: [
    defineField({
      name: 'heroEyebrow',
      type: 'string',
      title: 'Hero Eyebrow',
      group: 'hero',
      initialValue: "— Milton Quran Institute —",
    }),
    defineField({
      name: 'heroTitle',
      type: 'string',
      title: 'Hero Title',
      group: 'hero',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      type: 'text',
      title: 'Hero Subtitle',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroCtaButtons',
      type: 'array',
      title: 'Hero CTA Buttons',
      group: 'hero',
      of: [{ type: 'ctaButton' }],
    }),
    defineField({
      name: 'programsSectionTitle',
      type: 'string',
      title: 'Programs Section Title',
      group: 'programs',
      initialValue: 'Our Programs',
    }),
    defineField({
      name: 'programsSectionSubtitle',
      type: 'text',
      title: 'Programs Section Subtitle',
      group: 'programs',
    }),
    defineField({
      name: 'programCategories',
      type: 'array',
      title: 'Program Categories (cards)',
      group: 'programs',
      of: [{ type: 'homeProgramCategory' }],
    }),
    defineField({
      name: 'whyChooseUsSectionTitle',
      type: 'string',
      title: 'Why Choose Us Section Title',
      group: 'whyChooseUs',
      initialValue: 'Why Choose Us',
    }),
    defineField({
      name: 'whyChooseUsSectionSubtitle',
      type: 'text',
      title: 'Why Choose Us Section Subtitle',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'whyChooseUsItems',
      type: 'array',
      title: 'Why Choose Us Items',
      group: 'whyChooseUs',
      of: [{ type: 'whyChooseUsItem' }],
    }),
    defineField({
      name: 'ctaTitle',
      type: 'string',
      title: 'CTA Banner Title',
      group: 'cta',
    }),
    defineField({
      name: 'ctaSubtitle',
      type: 'text',
      title: 'CTA Banner Subtitle',
      group: 'cta',
    }),
    defineField({
      name: 'ctaButtons',
      type: 'array',
      title: 'CTA Banner Buttons',
      group: 'cta',
      of: [{ type: 'ctaButton' }],
    }),
    defineField({
      name: 'footerNote',
      type: 'text',
      title: 'Footer Note',
      group: 'cta',
      rows: 2,
      description: 'Optional short note above or near the CTA (e.g. seasonal message).',
    }),
  ],
});
